### ISSUE TITLE
Using internal pull-up resistors

### ISSUE THREAD

**Issue by bit2shift** [porrey/pcfan#1]
The circuitry can be simplified by using `INPUT_PULLUP` as the mode for the sensor pin.
ATMegas have 20kΩ internal pull-up resistors.

**Comment by porrey** [comment]
Thanks, I do agree. Since this was published as part of a Hackster article I like to keep the pull-ups external so that they are not missed by newbies. By the way, if you do not mind, posting this comment to the Hackster page could be helpful to others.
